### ISSUE TITLE
大佬，能不能做个类似的从onedrive bussniess备份到阿里云盘的操作，类似rclone的sync，最好兼容rclone的加密

### ISSUE THREAD

**Issue by ypq123456789** [ykxVK8yL5L/pikpak2aliyun#2]
如题，从pikpak转移个人感觉意义不大，因为pp本来容量就比阿里大（白嫖vip的话），小姐姐看起来只要翻墙也还方便，没必要非得备份到阿里。反而od e5这种个人存储的hs文件，需要找个备份的加密盘存储，国内环境看起来也快。

**Comment by ykxVK8yL5L** [comment]
不好意思现在才回复  onedrive备份到阿里云是不是有点简单了😂   我新添加了 rclone加密的actions你可以参考下 只要把onedrive的rclone配置添加进去 剩下的就是改rclone命令就好了 很简单的 关键还是挂载aliyunwebdav 挂在后一切都可以用rclone命令解决
